Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/http/server.py", line 1314, in <module>
    test(
  File "/usr/local/lib/python3.12/http/server.py", line 1261, in test
    with ServerClass(addr, HandlerClass) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/http/server.py", line 1308, in server_bind
    return super().server_bind()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/http/server.py", line 1314, in <module>
    test(
  File "/usr/local/lib/python3.12/http/server.py", line 1261, in test
    with ServerClass(addr, HandlerClass) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/http/server.py", line 1308, in server_bind
    return super().server_bind()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/http/server.py", line 1314, in <module>
    test(
  File "/usr/local/lib/python3.12/http/server.py", line 1261, in test
    with ServerClass(addr, HandlerClass) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/http/server.py", line 1308, in server_bind
    return super().server_bind()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/http/server.py", line 1314, in <module>
    test(
  File "/usr/local/lib/python3.12/http/server.py", line 1261, in test
    with ServerClass(addr, HandlerClass) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/http/server.py", line 1308, in server_bind
    return super().server_bind()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/http/server.py", line 1314, in <module>
    test(
  File "/usr/local/lib/python3.12/http/server.py", line 1261, in test
    with ServerClass(addr, HandlerClass) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/http/server.py", line 1308, in server_bind
    return super().server_bind()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/http/server.py", line 1314, in <module>
    test(
  File "/usr/local/lib/python3.12/http/server.py", line 1261, in test
    with ServerClass(addr, HandlerClass) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/http/server.py", line 1308, in server_bind
    return super().server_bind()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/http/server.py", line 1314, in <module>
    test(
  File "/usr/local/lib/python3.12/http/server.py", line 1261, in test
    with ServerClass(addr, HandlerClass) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/http/server.py", line 1308, in server_bind
    return super().server_bind()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
10.12.67.76 - - [06/Sep/2025 14:35:34] "GET / HTTP/1.1" 200 -
10.12.67.76 - - [06/Sep/2025 14:35:35] code 404, message File not found
10.12.67.76 - - [06/Sep/2025 14:35:35] "GET /favicon.ico HTTP/1.1" 404 -
10.12.67.76 - - [06/Sep/2025 14:35:37] "GET /animals.json HTTP/1.1" 200 -
10.12.67.76 - - [06/Sep/2025 14:35:46] "GET /words/level1.json HTTP/1.1" 200 -
10.12.67.76 - - [06/Sep/2025 14:35:48] code 404, message File not found
10.12.67.76 - - [06/Sep/2025 14:35:48] "GET /favicon.ico HTTP/1.1" 404 -
10.12.67.76 - - [06/Sep/2025 14:36:09] "GET /words/level2.json HTTP/1.1" 200 -
10.12.67.76 - - [06/Sep/2025 14:36:09] "GET /words/level3.json HTTP/1.1" 200 -
10.12.199.86 - - [07/Sep/2025 02:38:53] "GET / HTTP/1.1" 200 -
10.12.199.86 - - [07/Sep/2025 02:38:53] code 404, message File not found
10.12.199.86 - - [07/Sep/2025 02:38:53] "GET /favicon.ico HTTP/1.1" 404 -
10.12.199.86 - - [07/Sep/2025 02:38:55] "GET /animals.json HTTP/1.1" 304 -
10.12.199.86 - - [07/Sep/2025 02:39:02] code 404, message File not found
10.12.199.86 - - [07/Sep/2025 02:39:02] "GET /words/level1.json HTTP/1.1" 404 -
10.12.199.86 - - [07/Sep/2025 02:39:04] code 404, message File not found
10.12.199.86 - - [07/Sep/2025 02:39:04] "GET /words/level1.json HTTP/1.1" 404 -
10.12.199.86 - - [07/Sep/2025 02:39:10] "GET /subjects/english/level1.json HTTP/1.1" 200 -
10.12.199.86 - - [07/Sep/2025 02:39:10] "GET /subjects/english/level2.json HTTP/1.1" 200 -
10.12.199.86 - - [07/Sep/2025 02:39:10] "GET /subjects/english/level3.json HTTP/1.1" 200 -
10.12.199.86 - - [07/Sep/2025 02:39:10] code 404, message File not found
10.12.199.86 - - [07/Sep/2025 02:39:10] "GET /words/level1.json HTTP/1.1" 404 -
10.12.199.86 - - [07/Sep/2025 02:39:12] code 404, message File not found
10.12.199.86 - - [07/Sep/2025 02:39:12] "GET /words/level1.json HTTP/1.1" 404 -
10.12.199.86 - - [07/Sep/2025 02:39:14] code 404, message File not found
10.12.199.86 - - [07/Sep/2025 02:39:14] "GET /words/level2.json HTTP/1.1" 404 -
10.12.199.86 - - [07/Sep/2025 02:39:14] code 404, message File not found
10.12.199.86 - - [07/Sep/2025 02:39:14] "GET /words/level3.json HTTP/1.1" 404 -
10.12.199.86 - - [07/Sep/2025 02:39:15] code 404, message File not found
10.12.199.86 - - [07/Sep/2025 02:39:15] "GET /words/level1.json HTTP/1.1" 404 -
10.12.199.86 - - [07/Sep/2025 02:39:16] code 404, message File not found
10.12.199.86 - - [07/Sep/2025 02:39:16] "GET /words/level1.json HTTP/1.1" 404 -
10.12.199.86 - - [07/Sep/2025 02:39:16] code 404, message File not found
10.12.199.86 - - [07/Sep/2025 02:39:16] "GET /words/level2.json HTTP/1.1" 404 -
10.12.199.86 - - [07/Sep/2025 02:39:17] code 404, message File not found
10.12.199.86 - - [07/Sep/2025 02:39:17] "GET /words/level3.json HTTP/1.1" 404 -
10.12.199.86 - - [07/Sep/2025 02:39:18] code 404, message File not found
10.12.199.86 - - [07/Sep/2025 02:39:18] "GET /words/level1.json HTTP/1.1" 404 -
10.12.199.86 - - [07/Sep/2025 02:40:44] "GET / HTTP/1.1" 200 -
10.12.199.86 - - [07/Sep/2025 02:40:45] code 404, message File not found
10.12.199.86 - - [07/Sep/2025 02:40:45] "GET /favicon.ico HTTP/1.1" 404 -
10.12.199.86 - - [07/Sep/2025 02:40:45] "GET /animals.json HTTP/1.1" 200 -
